/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.github.jaxrs.demo.service;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author moscac
 */
@javax.ws.rs.ApplicationPath("rest")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<>();
        resources.addAll(getRestResourceClasses());
        return resources;
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST
     * support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<>();

        return resources;
    }
    
}
